#워크플로의 이름(깃허브 액션 이름)
name: CI/CD

#워크플로가 시작될 조건 지정 -> main브랜치에 푸시할때마다 워크플로 시작하도록 지정
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #실행 환경 지정
    #실행 스탭 지정
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      #현재 시간 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@latest
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      #배포용 패키지 경로 지정
      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB.ENV

      #빈스토크 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@latest
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: board-springboot
          environment_name: Board-springboot-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: ./build/libs/${{ env.artifact }}